<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "t3fx_mailscanner"
 *
 * Auto generated by Extension Builder 2016-05-20
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Mail Scanner',
	'description' => 'Configuration module for the T3fx Mail Scanner',
	'category' => 'plugin',
	'author' => 'Steffen Hastädt',
	'author_email' => 'mailscanner@t3x.ch',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);