services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  T3x\T3xMailscanner\:
    resource: '../Classes/*'

  T3x\T3xMailscanner\Controller\Backend\MailScannerController:
    tags: ['backend.controller']
