services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  T3x\Mailscanner\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  T3x\Mailscanner\Controller\Backend\MailScannerController:
    tags: ['backend.controller']
    public: true

  T3x\Mailscanner\Domain\Repository\BlacklistRepository:
    public: true

  T3x\Mailscanner\Domain\Repository\ImportRepository:
    public: true

  T3x\Mailscanner\Domain\Repository\SenderRepository:
    public: true
